// Code generated by protoc-gen-go. DO NOT EDIT.
// source: municiones.proto

//poner en el paquete correspondiente este archivo después

package municiones_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SolicitudMunicion struct {
	IdEquipo             int32    `protobuf:"varint,1,opt,name=id_equipo,json=idEquipo,proto3" json:"id_equipo,omitempty"`
	CantidadAt           int32    `protobuf:"varint,2,opt,name=cantidad_at,json=cantidadAt,proto3" json:"cantidad_at,omitempty"`
	CantidadMp           int32    `protobuf:"varint,3,opt,name=cantidad_mp,json=cantidadMp,proto3" json:"cantidad_mp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolicitudMunicion) Reset()         { *m = SolicitudMunicion{} }
func (m *SolicitudMunicion) String() string { return proto.CompactTextString(m) }
func (*SolicitudMunicion) ProtoMessage()    {}
func (*SolicitudMunicion) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ddb65b02222216f, []int{0}
}

func (m *SolicitudMunicion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolicitudMunicion.Unmarshal(m, b)
}
func (m *SolicitudMunicion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolicitudMunicion.Marshal(b, m, deterministic)
}
func (m *SolicitudMunicion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolicitudMunicion.Merge(m, src)
}
func (m *SolicitudMunicion) XXX_Size() int {
	return xxx_messageInfo_SolicitudMunicion.Size(m)
}
func (m *SolicitudMunicion) XXX_DiscardUnknown() {
	xxx_messageInfo_SolicitudMunicion.DiscardUnknown(m)
}

var xxx_messageInfo_SolicitudMunicion proto.InternalMessageInfo

func (m *SolicitudMunicion) GetIdEquipo() int32 {
	if m != nil {
		return m.IdEquipo
	}
	return 0
}

func (m *SolicitudMunicion) GetCantidadAt() int32 {
	if m != nil {
		return m.CantidadAt
	}
	return 0
}

func (m *SolicitudMunicion) GetCantidadMp() int32 {
	if m != nil {
		return m.CantidadMp
	}
	return 0
}

type RespuestaSolicitud struct {
	Aprobado             bool     `protobuf:"varint,1,opt,name=aprobado,proto3" json:"aprobado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespuestaSolicitud) Reset()         { *m = RespuestaSolicitud{} }
func (m *RespuestaSolicitud) String() string { return proto.CompactTextString(m) }
func (*RespuestaSolicitud) ProtoMessage()    {}
func (*RespuestaSolicitud) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ddb65b02222216f, []int{1}
}

func (m *RespuestaSolicitud) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespuestaSolicitud.Unmarshal(m, b)
}
func (m *RespuestaSolicitud) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespuestaSolicitud.Marshal(b, m, deterministic)
}
func (m *RespuestaSolicitud) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespuestaSolicitud.Merge(m, src)
}
func (m *RespuestaSolicitud) XXX_Size() int {
	return xxx_messageInfo_RespuestaSolicitud.Size(m)
}
func (m *RespuestaSolicitud) XXX_DiscardUnknown() {
	xxx_messageInfo_RespuestaSolicitud.DiscardUnknown(m)
}

var xxx_messageInfo_RespuestaSolicitud proto.InternalMessageInfo

func (m *RespuestaSolicitud) GetAprobado() bool {
	if m != nil {
		return m.Aprobado
	}
	return false
}

func init() {
	proto.RegisterType((*SolicitudMunicion)(nil), "munition.SolicitudMunicion")
	proto.RegisterType((*RespuestaSolicitud)(nil), "munition.RespuestaSolicitud")
}

func init() {
	proto.RegisterFile("municiones.proto", fileDescriptor_2ddb65b02222216f)
}

var fileDescriptor_2ddb65b02222216f = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x4a, 0xc4, 0x40,
	0x10, 0xc6, 0x39, 0x45, 0x59, 0xc7, 0x42, 0x9d, 0x2a, 0xdc, 0x09, 0xca, 0x55, 0x56, 0x41, 0xf4,
	0x09, 0x54, 0xc4, 0x2a, 0x4d, 0xae, 0xbb, 0x26, 0x4c, 0xb2, 0x5b, 0x0c, 0x24, 0x3b, 0xeb, 0x66,
	0xd6, 0xe7, 0x17, 0x63, 0x92, 0x23, 0xa4, 0x5a, 0xbe, 0x3f, 0xcb, 0x8f, 0x6f, 0xe0, 0xb6, 0x4b,
	0x9e, 0x1b, 0x16, 0xef, 0xfa, 0x3c, 0x44, 0x51, 0x41, 0xf3, 0xe7, 0x28, 0x8b, 0xdf, 0x47, 0xb8,
	0x3b, 0x48, 0xcb, 0x0d, 0x6b, 0xb2, 0xc5, 0x58, 0xc3, 0x1d, 0x5c, 0xb1, 0xad, 0xdc, 0x77, 0xe2,
	0x20, 0xd9, 0xe6, 0x71, 0xf3, 0x74, 0x51, 0x1a, 0xb6, 0x9f, 0x83, 0xc6, 0x07, 0xb8, 0x6e, 0xc8,
	0x2b, 0x5b, 0xb2, 0x15, 0x69, 0x76, 0x36, 0xc4, 0x30, 0x59, 0x6f, 0xba, 0x28, 0x74, 0x21, 0x3b,
	0x5f, 0x16, 0x8a, 0xb0, 0x7f, 0x06, 0x2c, 0x5d, 0x1f, 0x92, 0xeb, 0x95, 0x66, 0x38, 0x6e, 0xc1,
	0x50, 0x88, 0x52, 0x93, 0xfd, 0x67, 0x9a, 0x72, 0xd6, 0x2f, 0x47, 0xb8, 0x39, 0xb8, 0xf8, 0xc3,
	0x56, 0xe2, 0x87, 0xf3, 0x1a, 0xa9, 0xc5, 0x2f, 0x80, 0xf1, 0x2f, 0xc5, 0x02, 0x77, 0xf9, 0xb4,
	0x28, 0x5f, 0xcd, 0xd9, 0xde, 0x9f, 0xc2, 0x35, 0xf7, 0x1d, 0x8f, 0xab, 0xfb, 0xd4, 0x97, 0xc3,
	0xf3, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xd1, 0x80, 0x2b, 0x3a, 0x01, 0x00, 0x00,
}
