// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: proto/municiones.proto

//poner en el paquete correspondiente este archivo después

package municiones_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolicitudMunicion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdEquipo   int32 `protobuf:"varint,1,opt,name=id_equipo,json=idEquipo,proto3" json:"id_equipo,omitempty"`
	CantidadAt int32 `protobuf:"varint,2,opt,name=cantidad_at,json=cantidadAt,proto3" json:"cantidad_at,omitempty"`
	CantidadMp int32 `protobuf:"varint,3,opt,name=cantidad_mp,json=cantidadMp,proto3" json:"cantidad_mp,omitempty"`
}

func (x *SolicitudMunicion) Reset() {
	*x = SolicitudMunicion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_municiones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudMunicion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudMunicion) ProtoMessage() {}

func (x *SolicitudMunicion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_municiones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudMunicion.ProtoReflect.Descriptor instead.
func (*SolicitudMunicion) Descriptor() ([]byte, []int) {
	return file_proto_municiones_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudMunicion) GetIdEquipo() int32 {
	if x != nil {
		return x.IdEquipo
	}
	return 0
}

func (x *SolicitudMunicion) GetCantidadAt() int32 {
	if x != nil {
		return x.CantidadAt
	}
	return 0
}

func (x *SolicitudMunicion) GetCantidadMp() int32 {
	if x != nil {
		return x.CantidadMp
	}
	return 0
}

type RespuestaSolicitud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aprobado bool `protobuf:"varint,1,opt,name=aprobado,proto3" json:"aprobado,omitempty"`
}

func (x *RespuestaSolicitud) Reset() {
	*x = RespuestaSolicitud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_municiones_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaSolicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaSolicitud) ProtoMessage() {}

func (x *RespuestaSolicitud) ProtoReflect() protoreflect.Message {
	mi := &file_proto_municiones_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaSolicitud.ProtoReflect.Descriptor instead.
func (*RespuestaSolicitud) Descriptor() ([]byte, []int) {
	return file_proto_municiones_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaSolicitud) GetAprobado() bool {
	if x != nil {
		return x.Aprobado
	}
	return false
}

var File_proto_municiones_proto protoreflect.FileDescriptor

var file_proto_municiones_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x72, 0x0a, 0x11, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x4d,
	0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x6e, 0x74, 0x69,
	0x64, 0x61, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61,
	0x64, 0x5f, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x6e, 0x74,
	0x69, 0x64, 0x61, 0x64, 0x4d, 0x70, 0x22, 0x30, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x61, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x64, 0x6f, 0x32, 0x5a, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x64, 0x6f, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x47, 0x0a, 0x0a, 0x53,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x4d, 0x12, 0x1b, 0x2e, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x4d, 0x75,
	0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x53, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x75, 0x64, 0x42, 0x12, 0x5a, 0x10, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_municiones_proto_rawDescOnce sync.Once
	file_proto_municiones_proto_rawDescData = file_proto_municiones_proto_rawDesc
)

func file_proto_municiones_proto_rawDescGZIP() []byte {
	file_proto_municiones_proto_rawDescOnce.Do(func() {
		file_proto_municiones_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_municiones_proto_rawDescData)
	})
	return file_proto_municiones_proto_rawDescData
}

var file_proto_municiones_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_municiones_proto_goTypes = []interface{}{
	(*SolicitudMunicion)(nil),  // 0: munition.SolicitudMunicion
	(*RespuestaSolicitud)(nil), // 1: munition.RespuestaSolicitud
}
var file_proto_municiones_proto_depIdxs = []int32{
	0, // 0: munition.ServidorCentral.SolicitarM:input_type -> munition.SolicitudMunicion
	1, // 1: munition.ServidorCentral.SolicitarM:output_type -> munition.RespuestaSolicitud
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_municiones_proto_init() }
func file_proto_municiones_proto_init() {
	if File_proto_municiones_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_municiones_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudMunicion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_municiones_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaSolicitud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_municiones_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_municiones_proto_goTypes,
		DependencyIndexes: file_proto_municiones_proto_depIdxs,
		MessageInfos:      file_proto_municiones_proto_msgTypes,
	}.Build()
	File_proto_municiones_proto = out.File
	file_proto_municiones_proto_rawDesc = nil
	file_proto_municiones_proto_goTypes = nil
	file_proto_municiones_proto_depIdxs = nil
}
